### PR TITLE
prep-javascript-functions

### PR DESCRIPTION
**Pull request by bug-smith**
Screenshot 2023-04-21 at 9 04 01 AM

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
make sure you call all of the functions with appropriate arguments and console log them as indicated in the instructions. Code is looking good!

**Comment by bug-smith** [comment]
Screenshot 2023-04-21 at 10 38 12 AM

Code has been updated to use arguments to print out the respected on page load using console.log for each function

Makes total sense, the automated results are a bit nicer than manually entering into the console, ahha.

Seems like more manageable/usable, too, for both sides.

Appreciate your help as always, Brett!

**Review by Zhiwutian — COMMENTED** [review]
👍🏼

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
